Ignore PostgreSQL zone changes in lifecycle
Add lifecycle block to ignore zone attribute changes on PostgreSQL server.

Issue: Azure PostgreSQL Flexible Server gets assigned a zone automatically,
but trying to change it requires high availability configuration.
Since we don't use HA, we ignore zone changes to prevent drift errors.

Fixes error:
  Error: zone can only be changed when exchanged with
  high_availability.0.standby_availability_zone